# Generated by Django 4.0.3 on 2022-03-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_bot', '0002_dictionary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name': 'dictionary', 'verbose_name_plural': 'Dictionaries'},
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
