# Generated by Django 4.0.3 on 2022-03-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_bot', '0003_alter_dictionary_options_alter_dictionary_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='translated_word_lang_code',
            field=models.CharField(max_length=5),
        ),
    ]
