# Generated by Django 4.0.3 on 2022-03-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_bot', '0004_alter_dictionary_translated_word_lang_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='original_word_lang_code',
            field=models.CharField(max_length=5),
        ),
    ]
