# Generated by Django 4.0.3 on 2022-03-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_bot', '0005_alter_dictionary_original_word_lang_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pending_state',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
