# Generated by Django 4.0.3 on 2022-04-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_bot', '0006_users_pending_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='native_language',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='target_language',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
